param(
    [string]$UrdfPath,
    [string]$ReportPath
)

$ErrorActionPreference = "Stop"

$isaacDir = $PSScriptRoot
if (-not $UrdfPath -or $UrdfPath.Trim().Length -eq 0) {
    $UrdfPath = Join-Path $isaacDir "..\urdf\generated\Domino_URDF_Parts_Combined_Final_description\urdf\Domino_URDF_Parts_Combined_Final.urdf"
}
if (-not $ReportPath -or $ReportPath.Trim().Length -eq 0) {
    $ReportPath = Join-Path $isaacDir "reports\domino-urdf-topology.md"
}

$resolvedUrdf = Resolve-Path $UrdfPath
[xml]$doc = Get-Content -Raw -LiteralPath $resolvedUrdf

$links = @($doc.robot.link)
$joints = @($doc.robot.joint)

$linkNames = @($links | ForEach-Object { [string]$_.name })
$jointRows = @($joints | ForEach-Object {
    $limitText = ""
    if ($_.limit) {
        $limitText = ("{0} to {1}" -f $_.limit.lower, $_.limit.upper)
    }
    [pscustomobject]@{
        Name = [string]$_.name
        Type = [string]$_.type
        Parent = [string]$_.parent.link
        Child = [string]$_.child.link
        Axis = [string]$_.axis.xyz
        Limit = $limitText
    }
})

$duplicateLinks = @(
    $linkNames |
        Group-Object |
        Where-Object { $_.Count -gt 1 } |
        Sort-Object Name
)

$childrenWithMultipleParents = @(
    $jointRows |
        Group-Object Child |
        Where-Object { $_.Count -gt 1 } |
        Sort-Object Name
)

$jointTypeCounts = @(
    $jointRows |
        Group-Object Type |
        Sort-Object Name
)

$knownLinks = @{}
foreach ($name in $linkNames) {
    if (-not $knownLinks.ContainsKey($name)) {
        $knownLinks[$name] = $true
    }
}

$orphanParents = @(
    $jointRows |
        Where-Object { -not $knownLinks.ContainsKey($_.Parent) } |
        Select-Object -ExpandProperty Parent -Unique |
        Sort-Object
)

$orphanChildren = @(
    $jointRows |
        Where-Object { -not $knownLinks.ContainsKey($_.Child) } |
        Select-Object -ExpandProperty Child -Unique |
        Sort-Object
)

$childSet = @{}
foreach ($row in $jointRows) {
    if (-not $childSet.ContainsKey($row.Child)) {
        $childSet[$row.Child] = $true
    }
}

$rootCandidates = @(
    $knownLinks.Keys |
        Where-Object { -not $childSet.ContainsKey($_) } |
        Sort-Object
)

$drivenCandidates = @(
    $jointRows |
        Where-Object { $_.Type -eq "revolute" -and $_.Limit.Trim().Length -gt 0 } |
        Sort-Object Name
)

$passiveCandidates = @(
    $jointRows |
        Where-Object { $_.Type -eq "continuous" -or $_.Limit.Trim().Length -eq 0 } |
        Sort-Object Name
)

$totalMass = 0.0
foreach ($link in $links) {
    if ($link.inertial -and $link.inertial.mass) {
        $totalMass += [double]$link.inertial.mass.value
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Domino URDF Topology Report")
$lines.Add("")
$lines.Add("Generated by simulation/isaac/analyze-domino-urdf.ps1.")
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add(("| Metric | Value |"))
$lines.Add(("| --- | ---: |"))
$lines.Add(("| Link elements | {0} |" -f $links.Count))
$lines.Add(("| Unique link names | {0} |" -f ($knownLinks.Keys.Count)))
$lines.Add(("| Joint elements | {0} |" -f $joints.Count))
$lines.Add(("| Duplicate link-name groups | {0} |" -f $duplicateLinks.Count))
$lines.Add(("| Child links with multiple incoming joints | {0} |" -f $childrenWithMultipleParents.Count))
$lines.Add(("| Root candidates | {0} |" -f $rootCandidates.Count))
$lines.Add(("| Total mass from link inertials, including duplicated link elements | {0:N3} kg |" -f $totalMass))
$lines.Add("")

if ($duplicateLinks.Count -gt 0 -or $childrenWithMultipleParents.Count -gt 0) {
    $lines.Add("**Direct Isaac tree import status:** blocked for a training-ready articulation. The export contains repeated link names and loop-style child reuse, so it should be treated as a reference export until it is rewritten into a clean tree plus explicit passive loop constraints.")
} else {
    $lines.Add("**Direct Isaac tree import status:** no duplicate link names or multi-parent child links were detected. Joint axes, limits, inertias, collisions, and drive setup still need validation in Isaac.")
}

$lines.Add("")
$lines.Add("## Joint Type Counts")
$lines.Add("")
$lines.Add("| Type | Count |")
$lines.Add("| --- | ---: |")
foreach ($group in $jointTypeCounts) {
    $lines.Add(("| {0} | {1} |" -f $group.Name, $group.Count))
}

$lines.Add("")
$lines.Add("## Duplicate Link Names")
$lines.Add("")
if ($duplicateLinks.Count -eq 0) {
    $lines.Add("None detected.")
} else {
    $lines.Add("| Link name | Count |")
    $lines.Add("| --- | ---: |")
    foreach ($group in $duplicateLinks) {
        $lines.Add(("| {0} | {1} |" -f $group.Name, $group.Count))
    }
}

$lines.Add("")
$lines.Add("## Child Links With Multiple Incoming Joints")
$lines.Add("")
if ($childrenWithMultipleParents.Count -eq 0) {
    $lines.Add("None detected.")
} else {
    $lines.Add("| Child link | Incoming joints | Parents |")
    $lines.Add("| --- | --- | --- |")
    foreach ($group in $childrenWithMultipleParents) {
        $rows = @($group.Group)
        $jointList = ($rows | ForEach-Object { $_.Name }) -join ", "
        $parentList = ($rows | ForEach-Object { $_.Parent } | Sort-Object -Unique) -join ", "
        $lines.Add(("| {0} | {1} | {2} |" -f $group.Name, $jointList, $parentList))
    }
}

$lines.Add("")
$lines.Add("## Root Candidates")
$lines.Add("")
if ($rootCandidates.Count -eq 0) {
    $lines.Add("None detected.")
} else {
    foreach ($root in $rootCandidates) {
        $lines.Add(("- {0}" -f $root))
    }
}

$lines.Add("")
$lines.Add("## Orphan Link References")
$lines.Add("")
if ($orphanParents.Count -eq 0 -and $orphanChildren.Count -eq 0) {
    $lines.Add("No parent or child joint references point to missing link names.")
} else {
    if ($orphanParents.Count -gt 0) {
        $lines.Add("Missing parent links:")
        foreach ($name in $orphanParents) {
            $lines.Add(("- {0}" -f $name))
        }
    }
    if ($orphanChildren.Count -gt 0) {
        $lines.Add("Missing child links:")
        foreach ($name in $orphanChildren) {
            $lines.Add(("- {0}" -f $name))
        }
    }
}

$lines.Add("")
$lines.Add("## Driven Joint Candidates")
$lines.Add("")
$lines.Add("These are the revolute joints with limits in the current CAD export. They are candidates for the controlled articulation model, not final Isaac joint names.")
$lines.Add("")
$lines.Add("| Joint | Parent | Child | Axis | Limit rad |")
$lines.Add("| --- | --- | --- | --- | --- |")
foreach ($row in $drivenCandidates) {
    $lines.Add(("| {0} | {1} | {2} | {3} | {4} |" -f $row.Name, $row.Parent, $row.Child, $row.Axis, $row.Limit))
}

$lines.Add("")
$lines.Add("## Passive / Loop Joint Candidates")
$lines.Add("")
$lines.Add("These joints should be reviewed as passive linkage pins or loop-closure constraints. They should not all become policy action dimensions.")
$lines.Add("")
$lines.Add("| Joint | Type | Parent | Child | Axis |")
$lines.Add("| --- | --- | --- | --- | --- |")
foreach ($row in $passiveCandidates) {
    $lines.Add(("| {0} | {1} | {2} | {3} | {4} |" -f $row.Name, $row.Type, $row.Parent, $row.Child, $row.Axis))
}

$lines.Add("")
$lines.Add("## All Joints")
$lines.Add("")
$lines.Add("| Joint | Type | Parent | Child | Axis | Limit rad |")
$lines.Add("| --- | --- | --- | --- | --- | --- |")
foreach ($row in $jointRows) {
    $classification = $row.Limit
    if ($classification.Trim().Length -eq 0) {
        $classification = "-"
    }
    $lines.Add(("| {0} | {1} | {2} | {3} | {4} | {5} |" -f $row.Name, $row.Type, $row.Parent, $row.Child, $row.Axis, $classification))
}

$reportDir = Split-Path -Parent $ReportPath
if ($reportDir -and -not (Test-Path -LiteralPath $reportDir)) {
    New-Item -ItemType Directory -Force -Path $reportDir | Out-Null
}

Set-Content -LiteralPath $ReportPath -Value $lines -Encoding UTF8
Write-Host ("Wrote {0}" -f (Resolve-Path $ReportPath))
